#!/bin/bash

set -e -x

absolute_path() {
  (cd $1 && pwd)
}

function usage() {
  >&2 echo "
  Usage: $0 -d DIEGO_RELEASE_DIR -c CF_RELEASE_DIR (-l)

  -d diego release directory location
  -c cf release directory location
  -l legacy release versions"
  exit 1
}

function generate_component_manifest() {
  component=$1

  ./scripts/generate-deployment-manifest \
    ${TMP_DIR}/director.yml \
    manifest-generation/bosh-lite-stubs/property-overrides.yml \
    $CURRENT_DIR/${component}/instance-count-overrides.yml \
    manifest-generation/bosh-lite-stubs/persistent-disk-overrides.yml \
    $CURRENT_DIR/${component}/iaas-settings.yml \
    manifest-generation/bosh-lite-stubs/additional-jobs.yml \
    # manifest-generation/bosh-lite-stubs/release-versions.yml \
    $OUTPUT_DIR \
    > $TMP_DIR/${component}.yml

  spiff merge $TMP_DIR/${component}.yml $CURRENT_DIR/${component}/deployment-name.yml $LEGACY_STUBS > $OUTPUT_DIR/${component}.yml

  echo "Created manifest for ${component}: ${OUTPUT_DIR}/${component}.yml"
}

scripts_path=$(absolute_path `dirname $0`)

CURRENT_DIR=$(absolute_path $scripts_path/..)

while getopts "d:c:l" opt; do
  case $opt in
    d)
      DIEGO_RELEASE_DIR=$OPTARG
      ;;
    c)
      CF_RELEASE_DIR=$OPTARG
      ;;
    l)
      echo 'Using misc-stubs/legacy-releases.yml for legacy versioned releases'
      LEGACY_STUBS=$CURRENT_DIR/misc-stubs/legacy-releases.yml
      ;;
    \?)
      echo no dawg >&2
      ;;
  esac
done

OUTPUT_DIR=$CURRENT_DIR/manifests
TMP_DIR=`mktemp -d -t upgrade-stable-manifests.XXXXXXXXXXXX`

echo DIEGO_RELEASE_DIR=$DIEGO_RELEASE_DIR
echo CF_RELEASE_DIR=$CF_RELEASE_DIR

if [ ! -d "${DIEGO_RELEASE_DIR}" ]; then
  >&2 echo "Diego Release Directory '${DIEGO_RELEASE_DIR}' is not a directory"
  usage
fi

if [ ! -d "${CF_RELEASE_DIR}" ]; then
  >&2 echo "CF Release Directory '${CF_RELEASE_DIR}' is not a directory"
  usage
fi

mkdir -p $OUTPUT_DIR

DIRECTOR_UUID=$(bosh status --uuid)

echo "director_uuid: ${DIRECTOR_UUID}" > $TMP_DIR/director.yml

pushd $CF_RELEASE_DIR > /dev/null
  BOSH_RELEASES_DIR=$PWD/.. ./scripts/generate-bosh-lite-dev-manifest \
    ${CURRENT_DIR}/misc-stubs/diego-default.yml \
    ${LEGACY_STUBS}

  cp bosh-lite/deployments/cf.yml ${OUTPUT_DIR}/cf.yml
popd > /dev/null


pushd $DIEGO_RELEASE_DIR > /dev/null
  generate_component_manifest database
  generate_component_manifest brain-and-pals
  generate_component_manifest cell1
  generate_component_manifest cell2
popd > /dev/null
